apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3  # Number of Pods to create
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest  # Replace with your desired image
        ports:
        - containerPort: 80

---
apiVersion: v1
metadata:
  name:  my-app
  labels:
    app:  my-app
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app:  my-app
  type: LoadBalancer

